server:
  port: 3000

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

spring:
  data:
    mongodb:
      database: vuttr
      authentication-database: admin
      port: 27017
      host: localhost